# Generated by Django 4.2.6 on 2023-10-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_delete_discuss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
    ]
