# Generated by Django 4.2.6 on 2023-10-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_score_user_detail_submission_assignment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
