# Generated by Django 4.2.6 on 2023-10-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='assignment_score',
            new_name='assignment',
        ),
        migrations.AddField(
            model_name='score',
            name='grades',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='video/%y'),
        ),
    ]
