# Generated by Django 4.2.6 on 2023-10-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_course_discount_remove_course_featured_videos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
    ]
